---
 environment: production
 chdir: /app
 address: 127.0.0.1
 user: root
 group: root
 port: 8000
 pid: /app/thin.pid
 rackup: /app/config.ru
 log: /app/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 #daemonize: false
 #servers: 1
 #threaded: true
 no-epoll: true
